// Code generated by mockery v2.42.0. DO NOT EDIT.

package api

import (
	context "context"
	model "geolocation-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// GeolocationServiceMock is a mock struct for GeolocationService.
type GeolocationServiceMock struct {
	mock.Mock
}

// GetGeolocationByIpAddress mocks the GetGeolocationByIpAddress method.
func (m *GeolocationServiceMock) GetGeolocationByIpAddress(ctx context.Context, ipAddress string) (*model.Geolocation, error) {
	args := m.Called(ctx, ipAddress)
	return args.Get(0).(*model.Geolocation), args.Error(1)
}

// GetGeolocations mocks the GetGeolocations method.
func (m *GeolocationServiceMock) GetGeolocations(ctx context.Context, offset int, limit int) (*model.PageResponse, error) {
	args := m.Called(ctx, offset, limit)
	return args.Get(0).(*model.PageResponse), args.Error(1)
}
